#!/bin/sh
# Container entrypoint for jobSearchRust.
# Ensures JWT_SECRET is set to a unique random value per container when the
# operator hasn't supplied one, and refuses to start if it matches a known
# default sentinel value (defense against operators applying unmodified
# K8s manifests or older .env defaults).
#
# Generated by generator-jhipster-rust. Lint with: shellcheck docker-entrypoint.sh

set -eu

gen_random() {
  # POSIX-portable, no openssl dependency. /dev/urandom is always present on Linux.
  head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
}

is_sentinel() {
  case "${1:-}" in
    change-me-in-production)                            return 0 ;;
    change-me-in-production-use-a-secure-random-string) return 0 ;;
    your-super-secret-jwt-key-change-in-production)     return 0 ;;
    *-jwt-secret-key-change-in-production-*)            return 0 ;;
  esac
  return 1
}

# `[ -z ]` matches empty AND unset, so JWT_SECRET="" generates a random
# value here just like missing — deliberate. The Rust binary's
# is_sentinel("") rejects empty independently for the `cargo run` path.
if [ -z "${JWT_SECRET:-}" ]; then
  JWT_SECRET=$(gen_random)
  export JWT_SECRET
  echo "WARNING: JWT_SECRET unset; generated random per-container value. Set JWT_SECRET explicitly for production deployments." >&2
elif is_sentinel "$JWT_SECRET"; then
  echo "FATAL: JWT_SECRET is set to a known-default sentinel value. Refusing to start. See RELEASE_NOTES.md for migration guidance." >&2
  exit 1
else
  echo "INFO: JWT_SECRET supplied by operator." >&2
fi

exec "$@"
