-- Create job_offer table
CREATE TABLE job_offer (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    company VARCHAR(255),
    location VARCHAR(255),
    country VARCHAR(255),
    remote BOOLEAN,
    description VARCHAR(255),
    search_text VARCHAR(255),
    skills VARCHAR(255),
    metadata VARCHAR(255),
    raw_payload VARCHAR(255),
    content_hash VARCHAR(255),
    embedding_status VARCHAR(255),
    embedding_model VARCHAR(255),
    reindex_version INTEGER,
    retry_count INTEGER,
    indexing_error VARCHAR(255),
    source VARCHAR(255),
    source_id VARCHAR(255),
    apply_url VARCHAR(255),
    salary_min INTEGER,
    salary_max INTEGER,
    salary_currency VARCHAR(255),
    contract_type VARCHAR(255),
    experience_level VARCHAR(255),
    category VARCHAR(255),
    source_category VARCHAR(255),
    published_at TIMESTAMP,
    created_at TIMESTAMP,
    indexed_at TIMESTAMP,
    updated_at TIMESTAMP,
    expires_at TIMESTAMP,
    last_checked_at TIMESTAMP,
    created_by VARCHAR(50),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP);

-- Create indexes
CREATE INDEX idx_job_offer_id ON job_offer(id);
