use axum::{
    extract::{Path, Query},
    routing::get,
    Json, Router,
};
use serde::{Deserialize, Serialize};
use utoipa::{IntoParams, ToSchema};

use crate::errors::AppError;
use crate::services::AiService;
use crate::AppState;

/// Routes for AI prompt operations
pub fn routes() -> Router<AppState> {
    Router::new()
        .route("/prompt", get(prompt_query).post(prompt_json))
        .route("/prompt/:prompt", get(prompt_path))
}

/// Request query parameters for AI prompt endpoint
#[derive(Debug, Clone, Deserialize, IntoParams, ToSchema)]
pub struct PromptQuery {
    /// Prompt text to send to the AI agent
    pub prompt: Option<String>,
    /// Short alias for prompt
    pub q: Option<String>,
    /// Model name (defaults to the configured Mistral model)
    pub model: Option<String>,
    /// System prompt / preamble (defaults to "You are a helpful assistant.")
    pub preamble: Option<String>,
}

/// Request body for JSON POST AI prompt endpoint
#[derive(Debug, Clone, Deserialize, ToSchema)]
pub struct PromptRequest {
    /// Prompt text to send to the AI agent
    pub prompt: String,
    /// Model name (defaults to the configured Mistral model)
    pub model: Option<String>,
    /// System prompt / preamble (defaults to "You are a helpful assistant.")
    pub preamble: Option<String>,
}

/// Response payload from AI prompt
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct AiPromptResponse {
    /// The prompt sent to the model
    pub prompt: String,
    /// The response generated by the model
    pub response: String,
}

/// Send a prompt to the AI agent using query parameters
#[utoipa::path(
    get,
    path = "/api/ai/prompt",
    tag = "ai",
    params(
        ("prompt" = Option<String>, Query, description = "Prompt text to send to the AI agent"),
        ("q" = Option<String>, Query, description = "Alternative query parameter for prompt text"),
        ("model" = Option<String>, Query, description = "Model name (defaults to the configured Mistral model)"),
        ("preamble" = Option<String>, Query, description = "System prompt / preamble")
    ),
    responses(
        (status = 200, description = "AI prompt response", body = AiPromptResponse),
        (status = 400, description = "Bad request if prompt is missing"),
        (status = 500, description = "Internal error during prompt execution")
    )
)]
pub async fn prompt_query(
    Query(query): Query<PromptQuery>,
) -> Result<Json<AiPromptResponse>, AppError> {
    let prompt_text = query
        .prompt
        .or(query.q)
        .filter(|s| !s.trim().is_empty())
        .ok_or_else(|| AppError::BadRequest("Missing required 'prompt' or 'q' URL parameter".to_string()))?;

    let default_model = AiService::default_model();
    let model = query.model.as_deref().unwrap_or(&default_model);
    let preamble = query.preamble.as_deref().unwrap_or(crate::services::ai_service::DEFAULT_PREAMBLE);

    let response = AiService::prompt_with_model(&prompt_text, model, preamble).await?;

    Ok(Json(AiPromptResponse {
        prompt: prompt_text,
        response,
    }))
}

/// Send a prompt to the AI agent using path parameter
#[utoipa::path(
    get,
    path = "/api/ai/prompt/{prompt}",
    tag = "ai",
    params(
        ("prompt" = String, Path, description = "Prompt text to send to the AI agent")
    ),
    responses(
        (status = 200, description = "AI prompt response", body = AiPromptResponse),
        (status = 400, description = "Bad request if prompt is empty"),
        (status = 500, description = "Internal error during prompt execution")
    )
)]
pub async fn prompt_path(
    Path(prompt): Path<String>,
) -> Result<Json<AiPromptResponse>, AppError> {
    let prompt_text = prompt.trim().to_string();
    if prompt_text.is_empty() {
        return Err(AppError::BadRequest("Prompt path parameter cannot be empty".to_string()));
    }

    let response = AiService::prompt(&prompt_text).await?;

    Ok(Json(AiPromptResponse {
        prompt: prompt_text,
        response,
    }))
}

/// Send a prompt to the AI agent using JSON body
#[utoipa::path(
    post,
    path = "/api/ai/prompt",
    tag = "ai",
    request_body = PromptRequest,
    responses(
        (status = 200, description = "AI prompt response", body = AiPromptResponse),
        (status = 400, description = "Bad request if prompt is empty"),
        (status = 500, description = "Internal error during prompt execution")
    )
)]
pub async fn prompt_json(
    Json(payload): Json<PromptRequest>,
) -> Result<Json<AiPromptResponse>, AppError> {
    let prompt_text = payload.prompt.trim().to_string();
    if prompt_text.is_empty() {
        return Err(AppError::BadRequest("Prompt field cannot be empty".to_string()));
    }

    let default_model = AiService::default_model();
    let model = payload.model.as_deref().unwrap_or(&default_model);
    let preamble = payload.preamble.as_deref().unwrap_or(crate::services::ai_service::DEFAULT_PREAMBLE);

    let response = AiService::prompt_with_model(&prompt_text, model, preamble).await?;

    Ok(Json(AiPromptResponse {
        prompt: prompt_text,
        response,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::Router;
    use axum_test::TestServer;
    use crate::test_utils::create_test_state;

    fn create_test_app() -> TestServer {
        let state = create_test_state();
        let app = Router::new()
            .nest("/ai", routes())
            .with_state(state);
        TestServer::new(app).unwrap()
    }

    #[test]
    fn test_prompt_response_serialization() {
        let resp = AiPromptResponse {
            prompt: "What is Rust?".to_string(),
            response: "Rust is a systems programming language.".to_string(),
        };
        let json = serde_json::to_string(&resp).unwrap();
        assert!(json.contains("\"prompt\":\"What is Rust?\""));
        assert!(json.contains("\"response\":\"Rust is a systems programming language.\""));
    }

    #[test]
    fn test_prompt_query_deserialization() {
        let query: PromptQuery = serde_json::from_str(r#"{"prompt":"Hello","model":"mistral-small-latest"}"#).unwrap();
        assert_eq!(query.prompt.as_deref(), Some("Hello"));
        assert_eq!(query.model.as_deref(), Some("mistral-small-latest"));
        assert!(query.q.is_none());
        assert!(query.preamble.is_none());
    }

    #[test]
    fn test_prompt_request_deserialization() {
        let req: PromptRequest = serde_json::from_str(r#"{"prompt":"What is Rust?","model":"mistral-small-latest","preamble":"You are helpful"}"#).unwrap();
        assert_eq!(req.prompt, "What is Rust?");
        assert_eq!(req.model.as_deref(), Some("mistral-small-latest"));
        assert_eq!(req.preamble.as_deref(), Some("You are helpful"));
    }

    #[tokio::test]
    async fn test_prompt_query_missing_param_returns_bad_request() {
        let server = create_test_app();
        let response = server.get("/ai/prompt").await;
        response.assert_status_bad_request();
        let body: serde_json::Value = response.json();
        assert!(body["message"].as_str().unwrap().contains("Missing required 'prompt' or 'q' URL parameter"));
    }

    #[tokio::test]
    async fn test_prompt_query_empty_param_returns_bad_request() {
        let server = create_test_app();
        let response = server
            .get("/ai/prompt")
            .add_query_param("prompt", "   ")
            .await;
        response.assert_status_bad_request();
    }

    #[tokio::test]
    async fn test_prompt_json_empty_prompt_returns_bad_request() {
        let server = create_test_app();
        let response = server
            .post("/ai/prompt")
            .json(&serde_json::json!({
                "prompt": ""
            }))
            .await;
        response.assert_status_bad_request();
    }
}
