# This configuration is intended for development purpose.
# It's your responsibility to harden it for production.

name: job-jobsearchrust-ai

services:
  postgresql:
    image: paradedb/paradedb:latest
    container_name: job-search-ai-rust-postgres
    environment:
      - POSTGRES_USER=jobSearchRust
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '127.0.0.1:5438:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped
volumes:
  postgres-data:
