use chrono::NaiveDateTime;
use diesel::prelude::*;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// JobOffer entity
#[derive(Debug, Clone, Default, Queryable, Selectable, Identifiable, Serialize, Deserialize)]
#[diesel(table_name = crate::db::schema::job_offer)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct JobOffer {
    pub id: Uuid,
    pub title: String,
    pub company: Option<String>,
    pub location: Option<String>,
    pub country: Option<String>,
    pub remote: Option<bool>,
    pub description: Option<String>,
    pub search_text: Option<String>,
    pub skills: Option<String>,
    pub metadata: Option<String>,
    pub raw_payload: Option<String>,
    pub content_hash: Option<String>,
    pub embedding_status: Option<String>,
    pub embedding_model: Option<String>,
    pub reindex_version: Option<i32>,
    pub retry_count: Option<i32>,
    pub indexing_error: Option<String>,
    pub source: Option<String>,
    pub source_id: Option<String>,
    pub apply_url: Option<String>,
    pub salary_min: Option<i32>,
    pub salary_max: Option<i32>,
    pub salary_currency: Option<String>,
    pub contract_type: Option<String>,
    pub experience_level: Option<String>,
    pub category: Option<String>,
    pub source_category: Option<String>,
    pub published_at: Option<NaiveDateTime>,
    pub created_at: Option<NaiveDateTime>,
    pub indexed_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub expires_at: Option<NaiveDateTime>,
    pub last_checked_at: Option<NaiveDateTime>,
    pub created_by: Option<String>,
    pub created_date: Option<NaiveDateTime>,
    pub last_modified_by: Option<String>,
    pub last_modified_date: Option<NaiveDateTime>,
}

/// New JobOffer for insertion
#[derive(Debug, Clone, Insertable, Deserialize)]
#[diesel(table_name = crate::db::schema::job_offer)]
pub struct NewJobOffer {
    pub title: String,
    pub company: Option<String>,
    pub location: Option<String>,
    pub country: Option<String>,
    pub remote: Option<bool>,
    pub description: Option<String>,
    pub search_text: Option<String>,
    pub skills: Option<String>,
    pub metadata: Option<String>,
    pub raw_payload: Option<String>,
    pub content_hash: Option<String>,
    pub embedding_status: Option<String>,
    pub embedding_model: Option<String>,
    pub reindex_version: Option<i32>,
    pub retry_count: Option<i32>,
    pub indexing_error: Option<String>,
    pub source: Option<String>,
    pub source_id: Option<String>,
    pub apply_url: Option<String>,
    pub salary_min: Option<i32>,
    pub salary_max: Option<i32>,
    pub salary_currency: Option<String>,
    pub contract_type: Option<String>,
    pub experience_level: Option<String>,
    pub category: Option<String>,
    pub source_category: Option<String>,
    pub published_at: Option<NaiveDateTime>,
    pub created_at: Option<NaiveDateTime>,
    pub indexed_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub expires_at: Option<NaiveDateTime>,
    pub last_checked_at: Option<NaiveDateTime>,
    pub created_by: Option<String>,
    pub created_date: Option<NaiveDateTime>,
    pub last_modified_by: Option<String>,
    pub last_modified_date: Option<NaiveDateTime>,
}

/// JobOffer update changeset
#[derive(Debug, Clone, AsChangeset, Deserialize)]
#[diesel(table_name = crate::db::schema::job_offer)]
pub struct UpdateJobOffer {
    pub title: Option<String>,
    pub company: Option<String>,
    pub location: Option<String>,
    pub country: Option<String>,
    pub remote: Option<bool>,
    pub description: Option<String>,
    pub search_text: Option<String>,
    pub skills: Option<String>,
    pub metadata: Option<String>,
    pub raw_payload: Option<String>,
    pub content_hash: Option<String>,
    pub embedding_status: Option<String>,
    pub embedding_model: Option<String>,
    pub reindex_version: Option<i32>,
    pub retry_count: Option<i32>,
    pub indexing_error: Option<String>,
    pub source: Option<String>,
    pub source_id: Option<String>,
    pub apply_url: Option<String>,
    pub salary_min: Option<i32>,
    pub salary_max: Option<i32>,
    pub salary_currency: Option<String>,
    pub contract_type: Option<String>,
    pub experience_level: Option<String>,
    pub category: Option<String>,
    pub source_category: Option<String>,
    pub published_at: Option<NaiveDateTime>,
    pub created_at: Option<NaiveDateTime>,
    pub indexed_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub expires_at: Option<NaiveDateTime>,
    pub last_checked_at: Option<NaiveDateTime>,
    pub last_modified_by: Option<String>,
    pub last_modified_date: Option<NaiveDateTime>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_jobOffer_clone() {
        let entity = JobOffer {
            id: Uuid::nil(),
            title: "test".to_string(),
            company: None,
            location: None,
            country: None,
            remote: None,
            description: None,
            search_text: None,
            skills: None,
            metadata: None,
            raw_payload: None,
            content_hash: None,
            embedding_status: None,
            embedding_model: None,
            reindex_version: None,
            retry_count: None,
            indexing_error: None,
            source: None,
            source_id: None,
            apply_url: None,
            salary_min: None,
            salary_max: None,
            salary_currency: None,
            contract_type: None,
            experience_level: None,
            category: None,
            source_category: None,
            published_at: None,
            created_at: None,
            indexed_at: None,
            updated_at: None,
            expires_at: None,
            last_checked_at: None,
            created_by: Some("system".to_string()),
            created_date: None,
            last_modified_by: None,
            last_modified_date: None,
        };
        let cloned = entity.clone();
        assert_eq!(entity.id, cloned.id);
    }

    #[test]
    fn test_jobOffer_debug() {
        let entity = JobOffer {
            id: Uuid::nil(),
            title: "test".to_string(),
            company: None,
            location: None,
            country: None,
            remote: None,
            description: None,
            search_text: None,
            skills: None,
            metadata: None,
            raw_payload: None,
            content_hash: None,
            embedding_status: None,
            embedding_model: None,
            reindex_version: None,
            retry_count: None,
            indexing_error: None,
            source: None,
            source_id: None,
            apply_url: None,
            salary_min: None,
            salary_max: None,
            salary_currency: None,
            contract_type: None,
            experience_level: None,
            category: None,
            source_category: None,
            published_at: None,
            created_at: None,
            indexed_at: None,
            updated_at: None,
            expires_at: None,
            last_checked_at: None,
            created_by: None,
            created_date: None,
            last_modified_by: None,
            last_modified_date: None,
        };
        let debug_str = format!("{:?}", entity);
        assert!(debug_str.contains("JobOffer"));
    }

    #[test]
    fn test_new_jobOffer_creation() {
        let new_entity = NewJobOffer {
            title: "test".to_string(),
            company: None,
            location: None,
            country: None,
            remote: None,
            description: None,
            search_text: None,
            skills: None,
            metadata: None,
            raw_payload: None,
            content_hash: None,
            embedding_status: None,
            embedding_model: None,
            reindex_version: None,
            retry_count: None,
            indexing_error: None,
            source: None,
            source_id: None,
            apply_url: None,
            salary_min: None,
            salary_max: None,
            salary_currency: None,
            contract_type: None,
            experience_level: None,
            category: None,
            source_category: None,
            published_at: None,
            created_at: None,
            indexed_at: None,
            updated_at: None,
            expires_at: None,
            last_checked_at: None,
            created_by: Some("test_user".to_string()),
            created_date: None,
            last_modified_by: None,
            last_modified_date: None,
        };
        assert_eq!(new_entity.created_by, Some("test_user".to_string()));
    }

    #[test]
    fn test_update_jobOffer_creation() {
        let update = UpdateJobOffer {
            title: Some("updated".to_string()),
            company: Some("updated".to_string()),
            location: Some("updated".to_string()),
            country: Some("updated".to_string()),
            remote: Some(false),
            description: Some("updated".to_string()),
            search_text: Some("updated".to_string()),
            skills: Some("updated".to_string()),
            metadata: Some("updated".to_string()),
            raw_payload: Some("updated".to_string()),
            content_hash: Some("updated".to_string()),
            embedding_status: Some("updated".to_string()),
            embedding_model: Some("updated".to_string()),
            reindex_version: Some(999),
            retry_count: Some(999),
            indexing_error: Some("updated".to_string()),
            source: Some("updated".to_string()),
            source_id: Some("updated".to_string()),
            apply_url: Some("updated".to_string()),
            salary_min: Some(999),
            salary_max: Some(999),
            salary_currency: Some("updated".to_string()),
            contract_type: Some("updated".to_string()),
            experience_level: Some("updated".to_string()),
            category: Some("updated".to_string()),
            source_category: Some("updated".to_string()),
            published_at: Some(NaiveDateTime::parse_from_str("2024-01-01 00:00:00", "%Y-%m-%d %H:%M:%S").unwrap()),
            created_at: Some(NaiveDateTime::parse_from_str("2024-01-01 00:00:00", "%Y-%m-%d %H:%M:%S").unwrap()),
            indexed_at: Some(NaiveDateTime::parse_from_str("2024-01-01 00:00:00", "%Y-%m-%d %H:%M:%S").unwrap()),
            updated_at: Some(NaiveDateTime::parse_from_str("2024-01-01 00:00:00", "%Y-%m-%d %H:%M:%S").unwrap()),
            expires_at: Some(NaiveDateTime::parse_from_str("2024-01-01 00:00:00", "%Y-%m-%d %H:%M:%S").unwrap()),
            last_checked_at: Some(NaiveDateTime::parse_from_str("2024-01-01 00:00:00", "%Y-%m-%d %H:%M:%S").unwrap()),
            last_modified_by: Some("updater".to_string()),
            last_modified_date: None,
        };
        assert_eq!(update.last_modified_by, Some("updater".to_string()));
    }

    #[test]
    fn test_jobOffer_serialization() {
        let entity = JobOffer {
            id: Uuid::nil(),
            title: "test".to_string(),
            company: None,
            location: None,
            country: None,
            remote: None,
            description: None,
            search_text: None,
            skills: None,
            metadata: None,
            raw_payload: None,
            content_hash: None,
            embedding_status: None,
            embedding_model: None,
            reindex_version: None,
            retry_count: None,
            indexing_error: None,
            source: None,
            source_id: None,
            apply_url: None,
            salary_min: None,
            salary_max: None,
            salary_currency: None,
            contract_type: None,
            experience_level: None,
            category: None,
            source_category: None,
            published_at: None,
            created_at: None,
            indexed_at: None,
            updated_at: None,
            expires_at: None,
            last_checked_at: None,
            created_by: None,
            created_date: None,
            last_modified_by: None,
            last_modified_date: None,
        };
        let json = serde_json::to_string(&entity).unwrap();
        assert!(json.contains("\"id\":\"00000000-0000-0000-0000-000000000000\""));
    }
}
