//! jobSearchRust - Generated by JHipster
//!
//! A Rust web application built with Axum and Diesel.

pub mod config;
pub mod db;
pub mod dto;
pub mod errors;
pub mod handlers;
pub mod middleware;
pub mod models;
pub mod openapi;
pub mod services;

#[cfg(test)]
pub mod test_utils;

use config::AppConfig;
use db::connection::DbPool;

/// Application state shared across all handlers
#[derive(Clone)]
pub struct AppState {
    pub pool: DbPool,
    pub config: AppConfig,
}
